name: "Test Run"
on:
  push:
    paths:
      - "dist/index.js"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Run the Action
        id: run-action
        uses: ./
        with:
          personalAccessToken: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Test output
        run: echo ${{ steps.run-action.outputs.imageURL }}
